name: mrbj_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  carousel_slider: ^4.1.1
  google_sign_in: ^5.4.2
  get_storage: ^2.0.3
  eventsubscriber: ^2.1.3
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.1
  skeletons: ^0.0.3
  modal_bottom_sheet: ^2.1.2
  rxdart: ^0.27.5
  debounce_builder: ^0.9.0
  qr_flutter: ^4.0.0
  flutter_local_notifications: ^12.0.3
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  dropdown_formfield: ^0.1.4
  image_picker: ^0.8.6
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  overlay_support: ^2.1.0
  qr_code_scanner: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/banner1.jpg
    - lib/assets/images/banner2.jpg
    - lib/assets/icon/icon.png
