name: mrbj_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  persistent_bottom_nav_bar: ^4.0.2
  flutter_barcode_scanner: ^2.0.0
  carousel_slider: ^4.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/assets/images/banner1.jpg
    - lib/assets/images/banner2.jpg
    - lib/assets/images/banner3.png


